spring.application.name=time-deposit-kata
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/time_deposits}
spring.datasource.username=${DB_USER:deposits}
spring.datasource.password=${DB_PASSWORD:deposits}
